generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Content
    theme:                 sympal_admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sympal_content
    with_doctrine_route:     1

    config:
      actions: ~
      fields:
        site_id:
          label: Site
        content_type_id:
          label: Content Type
        master_menu_item_id:
          label: Under Menu Item
          help: Select the menu item this content record is associated with.
        custom_path:
          help: Custom path to be used to generate content record url.
        content_template_id:
          label: Content Template
          help: Choose the content template used to render this content record.
        layout:
          help: Choose the layout template used to render this content record.
        groups_list:
          label: Groups
          help: Choose the groups this content record is restricted to.
        permissions_list:
          label: Permissions
          help: Choose the permissions this content record is restricted to.
        created_by:
          help: Choose the user that created this record. It will default to the logged in user who created the record.
        is_published:
          help: Check to publish this content record. Checking this will automatically set the date published value to the current date. A content record will not be accessible to the public until the published date has been reached.
        date_published:
          help: Select the date this content record is to be published. This can be a date in the future and the content record will not be available until that date.
        slug:
          help: Enter the unique slug for this content record. This is a human readable string used to identify a content record and can be used in the routing custom path.
      form:
        display:
          "NONE": [created_by, is_published, date_published, slug]
          "Routing": [master_menu_item_id, custom_path]
          "Rendering": [content_template_id, layout]
          "Security": [groups_list, permissions_list]
      list:
        title: Manage Content
        display: [=title, Type, is_published, date_published]
        object_actions:
          view:
            action: view
          _edit:
          _delete:
      filter:
        display: [site_id, content_type_id]
      edit:
        title: "Editing Content #%%id%%"
        actions:
          _delete:
          _save:
          view:
            action: view
      new:
        title: Create New Content