generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ContentType
    theme:                 sympal_admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sympal_content_types
    with_doctrine_route:     1

    config:
      actions: ~
      fields: ~
      list:
        display: [=label]
        actions: []
      filter:
        display: [name, site_id]
      form:
        display: [label, description, default_path, layout slug]
        fields:
          layout:
            help: Choose the layout template used to render this content type.
          name:
            help: Enter the name of this content type. This is required to be the same name as the content model name.
          label:
            help: Enter the label used to render this content type.
          slug:
            help: Enter the unique slug used to identify this content type.
          default_path:
            help: Enter the route pattern used for linking to a single content type.
      edit:    ~
      new:     ~