generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Route
    theme:                 sympal_admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sympal_routes
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display: [_title, ContentType]
      filter:
        display: [name, content_id, content_type_id, site_id, table_method]
      form:    ~
      edit:    ~
      new:     ~
