generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Route
    theme:                 sympal_admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sympal_routes
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name, url, Type, ContentType]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
