all:
  sympal_config:
    plugin_api:
      username: 
      password: 
    slot_widgets:
      Signin Form: sympal_auth/signin_form
    content_formats: [html, atom, feed, atom1, rss, rss10, rss091, rss201, xml, yml, json]
    breadcrumbs_separator: ' / '
    i18n: true
    versioning: true
    versioned_models:
      Content: [created_by, is_published, date_published]
      ContentTranslation: [page_title, meta_keywords, meta_description]
      ContentSlotTranslation: [value]
      PageTranslation: [title]
      ContentTemplate: [body]
    internationalized_models:
      Content: [i18n_slug, page_title, meta_keywords, meta_description]
      ContentSlot: [value]
      MenuItem: [label]
      Page: [title]
    sluggable_models:
      Content: ~
      Site:
        fields: [title]
      ContentType:
        fields: [name]
      Route:
        fields: [name]
        unique: true
        uniqueBy: [site_id, name]
    default_from_email_address: noreply@sympalphp.org
    config_form_class: sfSympalConfigForm
    recaptcha_public_key: 6Ld2DgQAAAAAAApXLteupHPcbSxbSHkhNTuYLChX
    recaptcha_private_key: 6Ld2DgQAAAAAANIbaXJsFEBOyg56CL_ljy3APlPb
    language_codes: [en, fr]
    disallow_php_in_content: false
    default_layout: sympal
    rows_per_page: 10
    plugin_sources: ["http://svn.symfony-project.com/plugins"]
    markdown_styled_boxes: [quote, tip, caution, note]
    page_cache:
      enabled: true
      with_layout: true
      lifetime: 3600
      super_cache_enabled: true