all:
  sympal_config:
    menu_manager_class: sfSympalMenuSiteManager
    menu_class: sfSympalMenuSite
    yui_path: http://yui.yahooapis.com/2.7.0/build
    super_admin_signin_url: @sympal_dashboard
    enable_all_modules: true
    admin_module_web_dir: "/sfSympalPlugin"
    load_default_css: true
    plugin_api:
      username: 
      password: 
    slot_widgets:
      Signin Form: sympal_auth/signin_form
    content_formats: [html, atom, feed, atom1, rss, rss10, rss091, rss201, xml, yml, json]
    breadcrumbs_separator: ' / '
    i18n: true
    versioning: true
    versioned_models:
      Content: [created_by, is_published, date_published, slug]
      ContentTranslation: [page_title, meta_keywords, meta_description]
      ContentSlotTranslation: [value]
      PageTranslation: [title]
      ContentTemplate: [body]
    internationalized_models:
      Content: [i18n_slug, page_title, meta_keywords, meta_description]
      ContentSlot: [value]
      MenuItem: [label]
      Page: [title]
    sluggable_models:
      Content: ~
      Site:
        fields: [title]
        indexName: site_sluggable
      ContentType:
        fields: [name]
        indexName: content_type_sluggable
      Route:
        fields: [name]
        unique: true
        uniqueBy: [site_id, name]
        indexName: route_sluggable
    default_from_email_address: noreply@sympalphp.org
    config_form_class: sfSympalConfigForm
    recaptcha_public_key: 6Ld2DgQAAAAAAApXLteupHPcbSxbSHkhNTuYLChX
    recaptcha_private_key: 6Ld2DgQAAAAAANIbaXJsFEBOyg56CL_ljy3APlPb
    language_codes: [en, fr]
    disallow_php_in_content: false
    default_layout: sympal
    rows_per_page: 10
    plugin_sources: ["http://svn.symfony-project.com/plugins"]
    markdown_styled_boxes: [quote, tip, caution, note]