all:
  sympal_config:
    automatic_url_hierarchy: false
    load_all_modules: true
    get_cache_driver_callback: [sfSympalCache, getCacheDriver]
    menu_manager_class: sfSympalMenuSiteManager
    menu_class: sfSympalMenuSite
    breadcrumbs_class: sfSympalMenuBreadcrumbs
    yui_path: http://yui.yahooapis.com/2.7.0/build
    super_admin_signin_url: @sympal_dashboard
    enable_all_modules: true
    admin_module_web_dir: "/sfSympalPlugin"
    plugin_api:
      username: 
      password: 
    slot_widgets:
      Signin Form: sympal_auth/signin_form
    content_formats: [html, atom, feed, atom1, rss, rss10, rss091, rss201, xml, yml, json]
    breadcrumbs_separator: ' / '
    i18n: true
    internationalized_models:
      Content: [i18n_slug, page_title, meta_keywords, meta_description]
      ContentSlot: [value]
      MenuItem: [label]
      Page: [title]
    sluggable_models:
      Content:
        builder: [Content, slugBuilder]
      Site:
        fields: [title]
        indexName: site_sluggable
      ContentType:
        fields: [name]
        indexName: content_type_sluggable
    default_from_email_address: noreply@sympalphp.org
    config_form_class: sfSympalConfigForm
    recaptcha_public_key: 6Ld2DgQAAAAAAApXLteupHPcbSxbSHkhNTuYLChX
    recaptcha_private_key: 6Ld2DgQAAAAAANIbaXJsFEBOyg56CL_ljy3APlPb
    language_codes: [en, fr, es]
    disallow_php_in_content: true
    default_layout: sympal
    rows_per_page: 10
    plugin_sources: ["http://svn.symfony-project.com/plugins"]
    markdown_styled_boxes: [quote, tip, caution, note]