all:
  sympal_config:
    page_cache:
      enabled: false
      with_layout: false
      lifetime: 3600
    content_slot_types:
      Text:
        label: Single Line of Text
      RawHtml:
        label: Raw HTML
      Markdown:
        label: Markdown Editor
    check_for_upgrades_on_dashboard: false
    enable_all_modules: true
    get_cache_driver_callback: [sfSympalCache, getCacheDriver]
    menu_manager_class: sfSympalMenuSiteManager
    menu_class: sfSympalMenuSite
    breadcrumbs_class: sfSympalMenuBreadcrumbs
    super_admin_signin_url: @sympal_dashboard
    admin_module_web_dir: "/sfSympalPlugin"
    plugin_api:
      username: 
      password: 
    content_formats: [html, atom, feed, atom1, rss, rss10, rss091, rss201, xml, yml, json]
    breadcrumbs_separator: ' / '
    i18n: false
    internationalized_models:
      sfSympalContent: [i18n_slug, page_title, meta_keywords, meta_description]
      sfSympalContentSlot: [value]
      sfSympalMenuItem: [label]
      sfSympalPage: [title]
      sfSympalSite: [page_title, meta_keywords, meta_description]
    sluggable_models:
      sfSympalContent:
        builder: [sfSympalContent, slugBuilder]
      sfSympalSite:
        fields: [title]
        indexName: site_sluggable
      sfSympalContentType:
        fields: [label]
        indexName: content_type_sluggable
    default_from_email_address: noreply@sympalphp.org
    config_form_class: sfSympalConfigForm
    recaptcha_public_key: 6Ld2DgQAAAAAAApXLteupHPcbSxbSHkhNTuYLChX
    recaptcha_private_key: 6Ld2DgQAAAAAANIbaXJsFEBOyg56CL_ljy3APlPb
    language_codes: [en, fr, es]
    default_layout: sympal
    rows_per_page: 10
    plugin_sources: ["http://svn.symfony-project.com/plugins"]
    markdown_styled_boxes: [quote, tip, caution, note]