all:
  sympal_settings:
    language_codes: [en, fr, es]
    disallow_php_in_content: false
    default_layout: sympal
    rows_per_page: 10
    enable_menu_item_dropdown: true
    Page:
      enable_comments: true
    Comments:
      default_status: Approved
      enabled: true
      enable_recaptcha: true
      recaptcha_public_key: 6Ld2DgQAAAAAAApXLteupHPcbSxbSHkhNTuYLChX
      recaptcha_private_key: 6Ld2DgQAAAAAANIbaXJsFEBOyg56CL_ljy3APlPb 
      requires_auth: true
    I18n:
      enabled: true
      slots: true
      menus: true
    Page:
      enable_comments: true
    Event:
      enable_comments: true
    sympal_plugin_svn_sources: ["http://svn.symfony-project.com/plugins"]