all:
  sympal_config:
    # Configure forms that should have recaptcha enabled
    recaptcha_forms: [sfGuardRegisterForm]

    # The displayed name. You can change this to the project name you build on top of Sympal for example.
    sympal_name: Sympal

    # Configure Sympal themes
    themes:
      default:
        layout: default
        stylesheets:
          - /sfSympalPlugin/css/default.css
      sympal:
        layout: sympal
        stylesheets:
          - /sfSympalPlugin/css/sympal.css
      admin:
        layout: admin
        javascripts:
          - /sfSympalPlugin/js/jQuery.cookie.js
          - /sfSympalPlugin/fancybox/jquery.fancybox.js
          - /sfSympalAdminPlugin/js/admin.js
        stylesheets:
          - /sfSympalPlugin/fancybox/jquery.fancybox.css
          - /sfSympalAdminPlugin/css/global.css
          - /sfSympalAdminPlugin/css/default.css
          - /sfSympalAdminPlugin/css/admin.css
        callables:
          - [sfSympalToolkit, useJQuery]

    # Automatically set the response meta title based on the current content and menu item
    auto_seo:
      title: true
      title_format: %site_title% %separator% %ancestors%

    # Override the path of any bundled asset (js or css)
    # Used with the sfSympalConfig::getAssetPath() helper method
    # echo sfSympalConfig::getAssetPath('/sfSympalFrontendEditorPlugin/js/editor.js); // /js/my_editor.js
    asset_paths:
      #"/sfSympalFrontendEditorPlugin/js/editor.js": "/js/my_editor.js"

    # Customize the path to the loaded jQuery instance and any plugins
    jquery_reloaded:
      path: ~
      plugin_paths: ~

    # Enable and disable the markdown editor. When disabled a normal textarea is used
    enable_markdown_editor: true

    # Enable and disable the elastic textareas
    elastic_textareas: true

    # Configure Sympal page caching. Enabling this feature turns on page caching for all pages
    page_cache:
      super: false
      enabled: false
      with_layout: false
      lifetime: 3600

    # Configure and customize the available content slot types
    content_slot_types:
      #MySlotType:
      #  label: Label of My Slot Type
      #  widget_class: MySlotTypeWidget (defaults to sfWidgetFormSympalMySlotType)
      #  widget_options: []
      #  validator_class: MySlotTypeValidator (defaults to sfValidatorFormSympalMySlotType)
      #  validator_options: []
      Text:
        label: Single Line of Text
      RawHtml:
        label: Raw HTML
      Markdown:
        label: Markdown Editor
      TinyMCE:
        label: TinyMCE Rich Text Editor
        widget_class: sfWidgetFormTextareaTinyMCE
        widget_options:
          config: 'onchange_callback: "sympalTinyMCETriggerSave", handle_event_callback : "sympalHandleTinyMCEEvent"'

    # Enable and disable the check for upgrades via the web when on the Sympal dashboard
    check_for_upgrades_on_dashboard: false

    # Whether or not to enable all modules found in Sympal plugins
    enable_all_modules: true

    # Callback to retrieve the cache driver used for storing various Sympal cache entries
    get_cache_driver_callback: [sfSympalCache, getCacheDriver]

    # Customize the class used for managing menus
    menu_manager_class: sfSympalMenuSiteManager

    # Customize the menu class used to render site menus
    menu_class: sfSympalMenuSite

    # Customize the menu class used to render site breadcrumbs
    breadcrumbs_class: sfSympalMenuBreadcrumbs

    # Customize the admin module web directory
    admin_module_web_dir: "/sfSympalAdminPlugin"

    # Configure the Symfony Plugin API username and password
    # Required for the php symfony sympal:report-statistics task
    plugin_api:
      username:
      password:

    # Configure the available formats to render content in
    content_formats:
      - html
      - atom
      - feed
      - atom1
      - rss
      - rss10
      - rss091
      - rss201
      - xml
      - yml
      - json

    # Configure the string used to separate breadcrumb strings
    breadcrumbs_separator: ' / '

    # Configure internationalization
    i18n: false
    # Configure what models and fields get internationalized by Sympal
    internationalized_models:
      sfSympalContent: [i18n_slug, page_title, meta_keywords, meta_description]
      sfSympalContentSlot: [value]
      sfSympalMenuItem: [label]
      sfSympalPage: [title]
      sfSympalSite: [page_title, meta_keywords, meta_description]

    # Configure what models are sluggable
    sluggable_models:
      sfSympalContent:
        builder: [sfSympalContent, slugBuilder]
      sfSympalSite:
        fields: [title]
        indexName: site_sluggable
      sfSympalContentType:
        fields: [label]
        indexName: content_type_sluggable

    # Configure e-mail settings
    default_from_email_address: noreply@sympalphp.org

    # Configure form class used for editing the Sympal configuration from the web
    config_form_class: sfSympalConfigForm

    # Configure recaptcha from sfFormExtraPlugin
    recaptcha_public_key: 6Ld2DgQAAAAAAApXLteupHPcbSxbSHkhNTuYLChX
    recaptcha_private_key: 6Ld2DgQAAAAAANIbaXJsFEBOyg56CL_ljy3APlPb

    # Configure the available languages
    language_codes: [en, fr, es]

    # Configure the default theme to render Sympal with
    default_theme: default

    # Configure the name of the theme to use for Sympal admin areas
    admin_theme: admin

    # Configure the number of rows per page to use when using pagination
    rows_per_page: 10

    # Configure the sources to find Sympal plugins to download and install
    # This can be a SVN repository or a local directory.
    plugin_sources: ["http://svn.symfony-project.com/plugins"]

    # Allowed markdown styled boxes
    markdown_styled_boxes: [quote, tip, caution, note]