all:
  sympal_config:
    breadcrumbs_separator: ' / '
    i18n: true
    versioning: true
    versioned_models:
      Content: [created_by, is_published, date_published, slug, page_title, meta_keywords, meta_description]
      ContentSlotTranslation: [value]
      PageTranslation: [title]
      ContentTemplate: [body]
    internationalized_models:
      ContentSlot: [value]
      MenuItem: [label]
      Page: [title]
    default_from_email_address: noreply@sympalphp.org
    config_form_class: sfSympalConfigForm
    recaptcha_public_key: 6Ld2DgQAAAAAAApXLteupHPcbSxbSHkhNTuYLChX
    recaptcha_private_key: 6Ld2DgQAAAAAANIbaXJsFEBOyg56CL_ljy3APlPb
    language_codes: [en, fr]
    disallow_php_in_content: false
    default_layout: sympal
    rows_per_page: 10
    plugin_sources: ["http://svn.symfony-project.com/plugins"]
    markdown_styled_boxes: [quote, tip, caution, note]
    page_cache:
      enabled: true
      with_layout: true
      lifetime: 3600
      super_cache_enabled: true