all:
  sympal_settings:
    default_from_email_address: noreply@sympalphp.org
    config_form_class: sfSympalConfigForm
    recaptcha_public_key: 6Ld2DgQAAAAAAApXLteupHPcbSxbSHkhNTuYLChX
    recaptcha_private_key: 6Ld2DgQAAAAAANIbaXJsFEBOyg56CL_ljy3APlPb
    language_codes: [en, fr, es]
    disallow_php_in_content: false
    default_layout: sympal
    rows_per_page: 10
    I18n:
      enabled: true
      ContentSlot: true
      MenuItem: true
    sympal_plugin_svn_sources: ["http://svn.symfony-project.com/plugins"]
    markdown_styled_boxes: [quote, tip, caution, note]
    page_cache:
      enabled: true
      with_layout: true
      lifetime: 3600
      super_cache_enabled: true