<?php echo sfSympalToolkit::getRoutesYaml() ?>

sympal_change_language_form:
  url:   /change_language
  param: { module: sympal_default, action: change_language }
  requirements:
    sf_method: [post]

sympal_change_language:
  url:   /change_language/:language
  param: { module: sympal_default, action: change_language, language: en }

homepage:
  url:   /
  param: { module: sympal_content_renderer, action: index, result_type: object, sympal_content_type: sfSympalPage, sympal_content_slug: home }
  class: sfDoctrineRoute
  options:
    allow_empty: true
    model:  sfSympalContent
    type:   object
    method: getContent

sympal_homepage:
  url:   /
  param: { module: sympal_content_renderer, action: index, result_type: object, sympal_content_type: sfSympalPage, sympal_content_slug: home }
  class: sfDoctrineRoute
  options:
    allow_empty: true
    model:  sfSympalContent
    type:   object
    method: getContent