sympal_install_run:
  url:  /install/run
  param: { module: sympal_install, action: run }
  requirements:
    sf_method: [post]

sympal_install_plugins:
  url:  /install/plugins
  param: { module: sympal_install, action: install_plugins }

sympal_install:
  url:  /install
  param: { module: sympal_install, action: index }
  requirements:
    sf_method: [get]

sympal_check_for_updates:
  url:  /admin/upgrade/check
  param: { module: sympal_upgrade, action: check }

sympal_upgrade:
  url:  /admin/upgrade
  param: { module: sympal_upgrade, action: upgrade }

sympal_run_upgrade_tasks:
  url:  /admin/upgrade/tasks
  param: { module: sympal_upgrade, action: run_tasks }

sympal_save_form_tab_view_current_tab:
  url:  /form/save_current_tab/:name/:id
  param: { module: sympal_editor, action: save_form_current_tab }

sympal_editor_save_state:
  url:  /save_sympal_editor_state/:state
  param: { module: sympal_editor, action: save_editor_state }

sympal_dashboard:
  url:  /admin/dashboard
  param: { module: sympal_dashboard, action: index }

sympal_change_language_form:
  url:   /change_language
  param: { module: sympal_default, action: change_language }
  requirements:
    sf_method: [post]

sympal_change_language:
  url:   /change_language/:language
  param: { module: sympal_default, action: change_language, language: en }

sympal_edit_content_slot:
  url:   /edit_content_slot/:content_id/:id
  param: { module: sympal_edit_slot, action: edit_slot }
  class: sfDoctrineRoute
  options:
    model: sfSympalContentSlot
    type: object

sympal_save_content_slot:
  url:   /edit_content_slot/:content_id/:id/save
  param: { module: sympal_edit_slot, action: save_slot }
  class: sfDoctrineRoute
  options:
    model: sfSympalContentSlot
    type: object
  requirements:
    id: \d+
    sf_method: [POST]

sympal_preview_content_slot:
  url:   /preview_content_slot/:content_id/:id
  param: { module: sympal_edit_slot, action: preview_slot }
  class: sfDoctrineRoute
  options:
    model: sfSympalContentSlot
    type: object
  requirements:
    id: \d+
    sf_method: [POST]

sympal_change_column_content_slot_type:
  url:   /change_column_content_slot_type/:content_id/:id/:type/:name
  param: { module: sympal_edit_slot, action: change_content_slot_type, is_column: true }
  class: sfDoctrineRoute
  options:
    model: sfSympalContentSlot
    type: object

sympal_change_content_slot_type:
  url:   /change_content_slot_type/:content_id/:id/:type
  param: { module: sympal_edit_slot, action: change_content_slot_type }
  class: sfDoctrineRoute
  options:
    model: sfSympalContentSlot
    type: object

sympal_publish_content:
  url:   /publish_content/:id
  param: { module: sympal_editor, action: publish_content }
  class: sfDoctrineRoute
  options: { model: sfSympalContent, type: object }

sympal_unpublish_content:
  url:   /unpublish_content/:id
  param: { module: sympal_editor, action: unpublish_content }
  class: sfDoctrineRoute
  options: { model: sfSympalContent, type: object }

sympal_config:
  url:   /admin/configuration
  param: { module: sympal_config, action: index }

sympal_config_save:
  url:   /admin/configuration/save
  param: { module: sympal_config, action: save }

sympal_content_slot_types:
  class:                  sfDoctrineRouteCollection
  options:
    model:                sfSympalContentSlotType
    module:               sympal_content_slot_types
    prefix_path:          admin/content/slot_types
    with_wildcard_routes: true

sympal_content_types:
  class:                  sfDoctrineRouteCollection
  options:
    model:                sfSympalContentType
    module:               sympal_content_types
    prefix_path:          admin/content/types
    with_wildcard_routes: true

sympal_sites:
  class:                  sfDoctrineRouteCollection
  options:
    model:                sfSympalSite
    module:               sympal_sites
    prefix_path:          admin/sites
    with_wildcard_routes: true

sympal_content_menu_item:
  url:    /admin/content/:id/menu
  param: { module: sympal_content_menu_item, action: index }
  class: sfDoctrineRoute
  options:
    model:  sfSympalContent
    type:   object
  requirements:
    sf_method: [get, post]

sympal_content:
  class:                  sfDoctrineRouteCollection
  options:
    model:                sfSympalContent
    module:               sympal_content
    prefix_path:          admin/content
    with_wildcard_routes: true

sympal_content_view:
  url: /content/:slug
  param: { module: sympal_content_renderer, action: index, result_type: object, sympal_content_type: sfSympalPage }
  class: sfDoctrineRoute
  options:
    model:  sfSympalContent
    type:   object
    method: getContent

sympal_content_create_type:
  url:    /admin/content/create/:type
  param:  { module: sympal_content, action: create_type }

sympal_content_list_type:
  url:    /admin/content/list/:type
  param: { module: sympal_content, action: list_type }

<?php echo sfSympalToolkit::getRoutesYaml() ?>

homepage:
  url:   /
  param: { module: sympal_content_renderer, action: index, result_type: object, sympal_content_type: sfSympalPage, sympal_content_slug: home }
  class: sfDoctrineRoute
  options:
    model:  sfSympalContent
    type:   object
    method: getContent

sympal_homepage:
  url:   /
  param: { module: sympal_content_renderer, action: index, result_type: object, sympal_content_type: sfSympalPage, sympal_content_slug: home }
  class: sfDoctrineRoute
  options:
    model:  sfSympalContent
    type:   object
    method: getContent