homepage:
  url:   /
  param: { module: sympal_content_renderer, action: index, result_type: object, sympal_content_type: Page, sympal_content_slug: home }
  class: sfDoctrineRoute
  options:
    model:  Content
    type:   object
    method: getContent

sympal_homepage:
  url:   /
  param: { module: sympal_content_renderer, action: index, result_type: object, sympal_content_type: Page, sympal_content_slug: home }
  class: sfDoctrineRoute
  options:
    model:  Content
    type:   object
    method: getContent

sympal_install_run:
  url:  /install/run
  param: { module: sympal_install, action: run }
  requirements:
    sf_method: [post]

sympal_install:
  url:  /install
  param: { module: sympal_install, action: index }
  requirements:
    sf_method: [get]

sympal_version_history:
  url:   /version/:record_type/:record_id
  param: { module: sympal_editor, action: version_history }

sympal_revert_data:
  url:   /revert/:id
  param: { module: sympal_editor, action: revert_data }
  class: sfDoctrineRoute
  options:
    model: Version
    type: object

sympal_content_delete_route:
  url:  /content/delete_route/:id
  param: { module: sympal_content, action: delete_route }
  class: sfDoctrineRoute
  options: { model: Route, type: object }

sympal_save_form_tab_view_current_tab:
  url:  /form/save_current_tab/:name/:id
  param: { module: sympal_editor, action: save_form_current_tab }

sympal_tools_save_state:
  url:  /save_sympal_tools_state/:state
  param: { module: sympal_editor, action: save_tools_state }

sympal_dashboard:
  url:  /admin/dashboard
  param: { module: sympal_dashboard, action: index }

sympal_yui_image_uploader:
  url: /yui_image_uploader/upload
  param: { module: sympal_yui_image_uploader, action: upload }

sympal_change_language:
  url:   /change_language
  param: { module: sympal_editor, action: change_language }

sympal_signout:
  url:   /signout
  param: { module: sympal_auth, action: signout }

sympal_signin:
  url:   /signin
  param: { module: sympal_auth, action: signin }

sympal_toggle_edit:
  url:   /toggle_edit
  param: { module: sympal_editor, action: toggle_edit }

sympal_edit_column_content_slot:
  url:   /edit_column_content_slot/:id/:name
  param: { module: sympal_editor, action: edit_slot, is_column: true }
  class: sfDoctrineRoute
  options:
    model: ContentSlot
    type: object

sympal_edit_content_slot:
  url:   /edit_content_slot/:id
  param: { module: sympal_editor, action: edit_slot }
  class: sfDoctrineRoute
  options:
    model: ContentSlot
    type: object

sympal_save_content_slot:
  url:   /edit_content_slot/:id/save
  param: { module: sympal_editor, action: save_slot }
  class: sfDoctrineRoute
  options:
    model: ContentSlot
    type: object
  requirements:
    id: \d+
    sf_method: [POST]

sympal_preview_content_slot:
  url:   /preview_content_slot/:id
  param: { module: sympal_editor, action: preview_slot }
  class: sfDoctrineRoute
  options:
    model: ContentSlot
    type: object
  requirements:
    id: \d+
    sf_method: [POST]

sympal_change_column_content_slot_type:
  url:   /change_column_content_slot_type/:id/:type/:name
  param: { module: sympal_editor, action: change_content_slot_type, is_column: true }
  class: sfDoctrineRoute
  options:
    model: ContentSlot
    type: object

sympal_change_content_slot_type:
  url:   /change_content_slot_type/:id/:type
  param: { module: sympal_editor, action: change_content_slot_type }
  class: sfDoctrineRoute
  options:
    model: ContentSlot
    type: object

sympal_save_editor_panel_position:
  url:   /save_editor_panel_position
  param: { module: sympal_editor, action: save_panel_position }

sympal_publish_content:
  url:   /publish_content/:id
  param: { module: sympal_editor, action: publish_content }
  class: sfDoctrineRoute
  options: { model: Content, type: object }

sympal_unpublish_content:
  url:   /unpublish_content/:id
  param: { module: sympal_editor, action: unpublish_content }
  class: sfDoctrineRoute
  options: { model: Content, type: object }

sympal_config:
  url:   /admin/configuration
  param: { module: sympal_config, action: index }

sympal_config_save:
  url:   /admin/configuration/save
  param: { module: sympal_config, action: save }

sympal_content_slot_types:
  class:                  sfDoctrineRouteCollection
  options:
    model:                ContentSlotType
    module:               sympal_content_slot_types
    prefix_path:          admin/content/slot_types
    with_wildcard_routes: true

sympal_content_templates:
  class:                  sfDoctrineRouteCollection
  options:
    model:                ContentTemplate
    module:               sympal_content_templates
    prefix_path:          admin/content/templates
    with_wildcard_routes: true

sympal_content_types:
  class:                  sfDoctrineRouteCollection
  options:
    model:                ContentType
    module:               sympal_content_types
    prefix_path:          admin/content/types
    with_wildcard_routes: true

sympal_sites:
  class:                  sfDoctrineRouteCollection
  options:
    model:                Site
    module:               sympal_sites
    prefix_path:          admin/sites
    with_wildcard_routes: true

sympal_content:
  class:                  sfDoctrineRouteCollection
  options:
    model:                Content
    module:               sympal_content
    prefix_path:          admin/content
    with_wildcard_routes: true

sympal_content_view:
  url: /content/:slug
  param: { module: sympal_content_renderer, action: index, result_type: object, sympal_content_type: Page }
  class: sfDoctrineRoute
  options:
    model:  Content
    type:   object
    method: getContent

sympal_content_create_type:
  url:    /admin/content/create/:type
  param:  { module: sympal_content, action: create_type }

sympal_routes:
  class: sfDoctrineRouteCollection
  options:
    model:                Route
    module:               sympal_routes
    prefix_path:          admin/content/routes
    column:               id
    with_wildcard_routes: true

<?php $routes = Doctrine::getTable('Route')
  ->createQuery('r')
  ->innerJoin('r.ContentType t')
  ->leftJoin('r.Content c')
  ->innerJoin('r.Site s WITH s.slug = ?', sfConfig::get('sf_app'))
  ->orderBy('r.id DESC')
  ->execute(); ?>

<?php foreach ($routes as $route): ?> 
<?php echo $route['yaml'] ?> 
<?php endforeach; ?>