generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Entity
    theme:                 sympal_admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sympal_entities
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      form:    ~
      list:
        title: Manage Entities
        display: [=title, Type, is_published, date_published]
        object_actions:
          view:
            action: view
          _edit:
          _delete:
      filter:
        display: [site_id, entity_type_id]
      edit:
        title: "Editing Entity #%%id%%"
        actions:
          _delete:
          _save:
          view:
            action: view
      new:
        title: Create New Entity