Site:
  actAs:
    Sluggable:
      fields: [title]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    layout: string(255)
    title:
      type: string(255)
    description: clob

Content:
  actAs: [Sluggable, Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    site_id:
      type: integer(4)
      notnull: true
    content_type_id:
      type: integer(4)
      notnull: true
    content_template_id: integer(4)
    master_menu_item_id: integer(4)
    last_updated_by: integer(4)
    created_by: integer(4)
    locked_by: integer(4)
    is_published: boolean
    date_published: timestamp
    custom_path: string(255)
    layout: string(255)
  relations:
    MasterMenuItem:
      class: MenuItem
      local: master_menu_item_id
      onDelete: CASCADE
      foreignAlias: MasterContent
      foreignType: one
    LastUpdatedBy:
      class: sfGuardUser
      local: last_updated_by
      foreignAlias: LastUpdatedContent
      onDelete: SET NULL
    CreatedBy:
      class: sfGuardUser
      local: created_by
      foreignAlias: CreatedContent
      onDelete: SET NULL
    LockedBy:
      class: sfGuardUser
      local: locked_by
      foreignAlias: LockedContent
      onDelete: SET NULL
    Site:
      onDelete: CASCADE
    Type:
      class: ContentType
      onDelete: CASCADE
    Template:
      class: ContentTemplate
      onDelete: SET NULL
    Groups:
      class: sfGuardGroup
      local: content_id
      foreign: group_id
      refClass: ContentGroup
    Permissions:
      class: sfGuardPermission
      local: content_id
      foreign: permission_id
      refClass: ContentPermission
    Comments:
      class: Comment
      local: content_id
      foreign: comment_id
      refClass: ContentComment

ContentComment:
  columns:
    content_id:
      type: integer(4)
      primary: true
    comment_id:
      type: integer(4)
      primary: true
  relations:
    Content:
      foreignAlias: ContentComments
      onDelete: CASCADE
    Comment:
      foreignAlias: ContentComments
      onDelete: CASCADE

ContentType:
  actAs:
    Sluggable:
      fields: [name]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    label:
      type: string(255)
      notnull: true
    list_path: string(255)
    view_path: string(255)
    layout: string(255)

ContentTemplate:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    type:
      type: enum
      values: [View, List]
    content_type_id: integer(4)
    partial_path: string(255)
    component_path: string(255)
    body: clob
  relations:
    ContentType:
      foreignAlias: Templates

ContentSlot:
<?php if (sfSympalConfig::isI18nEnabled('slots')): ?> 
  actAs:
    I18n:
      fields: [value]
<?php endif; ?> 
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    content_id:
      type: integer(4)
      notnull: true
    content_slot_type_id:
      type: integer(4)
      notnull: true
    name:
      type: string(255)
      notnull: true
    value: clob
  relations:
    RelatedContent:
      class: Content
      foreignAlias: Slots
      onDelete: CASCADE
    Type:
      class: ContentSlotType
      foreignAlias: Slots
      onDelete: CASCADE

ContentSlotType:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true

ContentGroup:
  columns:
    content_id:
      primary: true
      type: integer(4)
    group_id:
      primary: true
      type: integer(4)
  relations:
    Content:
      foreignAlias: ContentGroups
      onDelete: CASCADE
    Group:
      class: sfGuardGroup
      local: group_id
      foreignAlias: ContentGroups
      onDelete: CASCADE

ContentPermission:
  columns:
    content_id:
      primary: true
      type: integer(4)
    permission_id:
      primary: true8
      type: integer(4)
  relations:
    Content:
      foreignAlias: ContentGroups
      onDelete: CASCADE
    Permission:
      class: sfGuardPermission
      local: permission_id
      foreignAlias: ContentPermissions
      onDelete: CASCADE