sfSympalSite:
  actAs: [sfSympalRecordTemplate]
  columns:
    layout: string(255)
    title:
      type: string(255)
      notnull: true
    description:
      type: clob
      notnull: true
    page_title: string(255)
    meta_keywords: string(500)
    meta_description: string(500)

sfSympalContent:
  actAs: [Timestampable, sfSympalRecordTemplate]
  columns:
    site_id:
      type: integer
      notnull: true
    content_type_id:
      type: integer
      notnull: true
    content_template_id: integer
    master_menu_item_id: integer
    last_updated_by_id: integer
    created_by_id:
      type: integer
      notnull: true
    is_published: boolean
    date_published: timestamp
    custom_path: string(255)
    layout: string(255)
    page_title: string(255)
    meta_keywords: string(500)
    meta_description: string(500)
    i18n_slug: string(255)
  indexes:
    is_published:
      fields: [is_published]
    date_published:
      fields: [date_published]
  relations:
    MasterMenuItem:
      class: sfSympalMenuItem
      local: master_menu_item_id
      onDelete: SET NULL
      foreignAlias: MasterContent
      foreignType: one
    LastUpdatedBy:
      class: sfGuardUser
      local: last_updated_by_id
      foreignAlias: LastUpdatedContent
      onDelete: SET NULL
    CreatedBy:
      class: sfGuardUser
      local: created_by_id
      foreignAlias: CreatedContent
      onDelete: CASCADE
    Site:
      local: site_id
      class: sfSympalSite
      onDelete: CASCADE
      foreignAlias: Content
    Type:
      local: content_type_id
      class: sfSympalContentType
      onDelete: CASCADE
      foreignAlias: Content
    Template:
      local: content_template_id
      class: sfSympalContentTemplate
      onDelete: SET NULL
      foreignAlias: Content
    Groups:
      class: sfGuardGroup
      local: content_id
      foreign: group_id
      refClass: sfSympalContentGroup
      foreignAlias: Content
    Permissions:
      class: sfGuardPermission
      local: content_id
      foreign: permission_id
      refClass: sfSympalContentPermission
      foreignAlias: Content
    Slots:
      class: sfSympalContentSlot
      refClass: sfSympalContentSlotRef
      local: content_id
      foreign: content_slot_id
      foreignAlias: Content

sfSympalContentType:
  actAs: [sfSympalRecordTemplate]
  columns:
    name:
      type: string(255)
      notnull: true
    description: clob
    label:
      type: string(255)
      notnull: true
    plugin_name:
      type: string(255)
      notnull: true
    default_path: string(255)
    layout: string(255)
    content_template_id: integer
  relations:
    Template:
      class: sfSympalContentTemplate
      local: content_template_id
      foreignAlias: ContentTypes
      onDelete: CASCADE
  indexes:
    content_type_name:
      fields: [name]

sfSympalContentTemplate:
  actAs: [sfSympalRecordTemplate]
  columns:
    name:
      type: string(255)
      notnull: true
    path: string(255)
    body: clob
    is_default:
      type: boolean
      default: false
    content_type_id:
      type: integer
      notnull: true
  relations:
    ContentType:
      local: content_type_id
      class: sfSympalContentType
      onDelete: CASCADE
      foreignAlias: ContentTemplates

sfSympalContentSlot:
  actAs: [sfSympalRecordTemplate]
  options:
    symfony:
      filter: false
  columns:
    content_slot_type_id:
      type: integer
      notnull: true
    is_column:
      type: boolean
      default: false
    render_function: string(255)
    name:
      type: string(255)
      notnull: true
    value: clob
  indexes:
    name:
      fields: [name]
  relations:
    Type:
      local: content_slot_type_id
      class: sfSympalContentSlotType
      foreignAlias: Slots
      onDelete: CASCADE

sfSympalContentSlotRef:
  actAs: [sfSympalRecordTemplate]
  options:
    symfony:
      form: false
      filter: false
  columns:
    content_slot_id:
      type: integer
      primary: true
    content_id:
      type: integer
      primary: true
  relations:
    Slot:
      class: sfSympalContentSlot
      local: content_slot_id
      foreignAlias: ContentSlotRefs
      onDelete: CASCADE
    Content:
      class: sfSympalContent
      local: content_id
      foreignAlias: ContentSlotRefs
      onDelete: CASCADE

sfSympalContentSlotType:
  actAs: [sfSympalRecordTemplate]
  columns:
    name:
      type: string(255)
      notnull: true
      unique: true
    is_internal:
      type: boolean
      default: 0

sfSympalContentGroup:
  actAs: [sfSympalRecordTemplate]
  options:
    symfony:
      form: false
      filter: false
  columns:
    content_id:
      primary: true
      type: integer
    group_id:
      primary: true
      type: integer
  relations:
    Content:
      local: content_id
      class: sfSympalContent
      foreignAlias: ContentGroups
      onDelete: CASCADE
    Group:
      class: sfGuardGroup
      local: group_id
      foreignAlias: ContentGroups
      onDelete: CASCADE

sfSympalContentPermission:
  actAs: [sfSympalRecordTemplate]
  options:
    symfony:
      form: false
      filter: false
  columns:
    content_id:
      primary: true
      type: integer
    permission_id:
      primary: true8
      type: integer
  relations:
    Content:
      class: sfSympalContent
      local: content_id
      foreignAlias: ContentGroups
      onDelete: CASCADE
    Permission:
      class: sfGuardPermission
      local: permission_id
      foreignAlias: ContentPermissions
      onDelete: CASCADE