Site:
  actAs:
    Sluggable:
      fields: [title]
  columns:
    layout: string(255)
    title:
      type: string(255)
      notnull: true
    description:
      type: clob
      notnull: true

Content:
  actAs: [Sluggable, Timestampable, sfSympalContent]
  columns:
    site_id:
      type: integer
      notnull: true
    content_type_id:
      type: integer
      notnull: true
    content_template_id: integer
    master_menu_item_id: integer
    last_updated_by: integer
    created_by:
      type: integer
      notnull: true
    locked_by: integer
    is_published: boolean
    date_published: timestamp
    custom_path: string(255)
    layout: string(255)
  relations:
    MasterMenuItem:
      class: MenuItem
      local: master_menu_item_id
      onDelete: CASCADE
      foreignAlias: MasterContent
      foreignType: one
    LastUpdatedBy:
      class: User
      local: last_updated_by
      foreignAlias: LastUpdatedContent
      onDelete: SET NULL
    CreatedBy:
      class: User
      local: created_by
      foreignAlias: CreatedContent
      onDelete: CASCADE
    LockedBy:
      class: User
      local: locked_by
      foreignAlias: LockedContent
      onDelete: SET NULL
    Site:
      onDelete: CASCADE
    Type:
      class: ContentType
      onDelete: CASCADE
    Template:
      class: ContentTemplate
      onDelete: SET NULL
    Groups:
      class: Group
      local: content_id
      foreign: group_id
      refClass: ContentGroup
    Permissions:
      class: Permission
      local: content_id
      foreign: permission_id
      refClass: ContentPermission

ContentType:
  actAs:
    Sluggable:
      fields: [name]
  columns:
    name:
      type: string(255)
      notnull: true
    description: clob
    label:
      type: string(255)
      notnull: true
    plugin_name: string(255)
    list_path: string(255)
    view_path: string(255)
    layout: string(255)

ContentTemplate:
  columns:
    name:
      type: string(255)
      notnull: true
    type:
      type: enum
      values: [View, List]
      notnull: true
    content_type_id:
      type: integer
      notnull: true
    partial_path: string(255)
    component_path: string(255)
    body: clob
  relations:
    ContentType:
      foreignAlias: Templates

ContentSlot:
<?php if (sfSympalConfig::isI18nEnabled('ContentSlot')): ?> 
  actAs:
    I18n:
      fields: [value]
<?php endif; ?> 
  columns:
    content_id:
      type: integer
      notnull: true
    content_slot_type_id:
      type: integer
      notnull: true
    is_column:
      type: boolean
      default: false
    render_function: string(255)
    name:
      type: string(255)
      notnull: true
    value: clob
  relations:
    RelatedContent:
      class: Content
      foreignAlias: Slots
      onDelete: CASCADE
    Type:
      class: ContentSlotType
      foreignAlias: Slots
      onDelete: CASCADE

ContentSlotType:
  columns:
    name:
      type: string(255)
      notnull: true

ContentGroup:
  columns:
    content_id:
      primary: true
      type: integer
    group_id:
      primary: true
      type: integer
  relations:
    Content:
      foreignAlias: ContentGroups
      onDelete: CASCADE
    Group:
      class: Group
      local: group_id
      foreignAlias: ContentGroups
      onDelete: CASCADE

ContentPermission:
  columns:
    content_id:
      primary: true
      type: integer
    permission_id:
      primary: true8
      type: integer
  relations:
    Content:
      foreignAlias: ContentGroups
      onDelete: CASCADE
    Permission:
      class: Permission
      local: permission_id
      foreignAlias: ContentPermissions
      onDelete: CASCADE

Route:
  actAs:
    Sluggable:
      fields: [name]
      unique: true
  columns:
    name:
      type: string(255)
      notnull: true
    url:
      type: string(255)
      notnull: true
    type:
      type: enum
      values: [List, View]
    content_id: integer
    content_type_id: integer
  relations:
    Content:
      foreignAlias: Routes
      onDelete: CASCADE
    ContentType:
      foreignAlias: Routes
      onDelete: CASCADE