Site:
  actAs:
    Sluggable:
      fields: [title]
    sfSympalRecord:
  columns:
    layout: string(255)
    title:
      type: string(255)
      notnull: true
    description:
      type: clob
      notnull: true
    page_title: string(255)
    meta_keywords: string(500)
    meta_description: string(500)

Content:
  actAs: [Sluggable, Timestampable, sfSympalRecord]
  columns:
    site_id:
      type: integer
      notnull: true
    content_type_id:
      type: integer
      notnull: true
    content_template_id: integer
    master_menu_item_id: integer
    last_updated_by: integer
    created_by:
      type: integer
      notnull: true
    locked_by: integer
    is_published: boolean
    date_published: timestamp
    custom_path: string(255)
    layout: string(255)
    page_title: string(255)
    meta_keywords: string(500)
    meta_description: string(500)
  indexes:
    is_published:
      fields: [is_published]
    date_published:
      fields: [date_published]
  relations:
    MasterMenuItem:
      class: MenuItem
      local: master_menu_item_id
      onDelete: CASCADE
      foreignAlias: MasterContent
      foreignType: one
    LastUpdatedBy:
      class: User
      local: last_updated_by
      foreignAlias: LastUpdatedContent
      onDelete: SET NULL
    CreatedBy:
      class: User
      local: created_by
      foreignAlias: CreatedContent
      onDelete: CASCADE
    LockedBy:
      class: User
      local: locked_by
      foreignAlias: LockedContent
      onDelete: SET NULL
    Site:
      onDelete: CASCADE
    Type:
      class: ContentType
      onDelete: CASCADE
    Template:
      class: ContentTemplate
      onDelete: SET NULL
    Groups:
      class: Group
      local: content_id
      foreign: group_id
      refClass: ContentGroup
    Permissions:
      class: Permission
      local: content_id
      foreign: permission_id
      refClass: ContentPermission

ContentType:
  actAs:
    Sluggable:
      fields: [name]
    sfSympalRecord:
  columns:
    name:
      type: string(255)
      notnull: true
      unique: true
    description: clob
    label:
      type: string(255)
      notnull: true
    plugin_name: string(255)
    default_path: string(255)
    layout: string(255)
    site_id: integer
  relations:
    Site:
      onDelete: CASCADE
      foreignAlias: ContentTypes
  indexes:
    name:
      fields: [name]

ContentTemplate:
  actAs: [sfSympalRecord]
  columns:
    name:
      type: string(255)
      notnull: true
    partial_path: string(255)
    component_path: string(255)
    body: clob
    is_default:
      type: boolean
      default: true
    content_type_id:
      type: integer
      notnull: true
  relations:
    ContentType:
      onDelete: CASCADE
      foreignAlias: ContentTemplates

ContentSlot:
  actAs:
    sfSympalRecord:
  columns:
    content_id:
      type: integer
      notnull: true
    content_slot_type_id:
      type: integer
      notnull: true
    is_column:
      type: boolean
      default: false
    render_function: string(255)
    name:
      type: string(255)
      notnull: true
    value: clob
  indexes:
    name:
      fields: [name]
  relations:
    RelatedContent:
      class: Content
      foreignAlias: Slots
      onDelete: CASCADE
    Type:
      class: ContentSlotType
      foreignAlias: Slots
      onDelete: CASCADE

ContentSlotType:
  actAs: [sfSympalRecord]
  columns:
    name:
      type: string(255)
      notnull: true
      unique: true
    is_internal:
      type: boolean
      default: 0
    site_id:
      type: integer
      notnull: true
  relations:
    Site:
      onDelete: CASCADE
      foreignAlias: ContentSlotTypes

ContentGroup:
  actAs: [sfSympalRecord]
  columns:
    content_id:
      primary: true
      type: integer
    group_id:
      primary: true
      type: integer
  relations:
    Content:
      foreignAlias: ContentGroups
      onDelete: CASCADE
    Group:
      class: Group
      local: group_id
      foreignAlias: ContentGroups
      onDelete: CASCADE

ContentPermission:
  actAs: [sfSympalRecord]
  columns:
    content_id:
      primary: true
      type: integer
    permission_id:
      primary: true8
      type: integer
  relations:
    Content:
      foreignAlias: ContentGroups
      onDelete: CASCADE
    Permission:
      class: Permission
      local: permission_id
      foreignAlias: ContentPermissions
      onDelete: CASCADE

Route:
  actAs:
    sfSympalRecord:
    Sluggable:
      fields: [name]
      unique: true
  columns:
    name:
      type: string(255)
      notnull: true
    url:
      type: string(255)
      notnull: true
    content_id: integer
    content_type_id:
      type: integer
      notnull: true
    yaml_override: clob
    site_id:
      type: integer
      notnull: true
    table_method: string(55)
  relations:
    Content:
      foreignAlias: Routes
      onDelete: CASCADE
    ContentType:
      foreignAlias: Routes
      onDelete: CASCADE
    Site:
      foreignAlias: Routes
      onDelete: CASCADE

Version:
  tableName: versions
  actAs:
    Timestampable:
      updated:
        disabled: true
  columns:
    record_id:
      type: integer
      notnull: true
    record_type:
      type: string(255)
      notnull: true
    created_by: integer
    num_changes:
      type: integer
      notnull: true
    version:
      type: integer
      notnull: true
  indexes:
    version:
      fields: [version]
    record_id:
      fields: [record_id]
    record_type:
      fields: [record_type]
  relations:
    CreatedBy:
      class: User
      local: created_by
      onDelete: CASCADE
      foreignAlias: Versions

VersionChange:
  columns:
    version_id:
      type: integer
      notnull: true
    field:
      type: string(255)
      notnull: true
    old_value: clob
    new_value: clob
  relations:
    Version:
      onDelete: CASCADE
      foreignAlias: Changes